### ISSUE TITLE
Integrate SASS in team project 

### ISSUE THREAD

**Issue by snrelghgub** [chingu-voyages/v9-toucans-team-12#21]
-to be installed at next meeting , taizy to setup on ashiya's pc remotely & also to demonstrate how much more convenient & organised CSS styling can be with it using one of its very awesome feature, nesting.

**Comment by DrewDen** [comment]
I think that this is something that we need to discuss because sass is new to all of us.  This might slow the process down on the project because this is something that we need to learn.  I feel like we are all putting time into learning bootstrap that adding a new language could put us further behind.
